Update prohibited strings
chromeos/chromeos.dev pull request #314
Opened 2022-03-04 00:12 UTC by nohe427

This updates the list of prohibited strings to be a close match to the
list that is maintained internally.

- Resolves #298

2022-03-08 17:19 UTC, Snugug requested changes
Thanks for working on this!

There are a few places where I think additions you've made are already covered, and where things can be combined. If you could take a look that'd be appreciated!

Thanks!

2022-03-08 17:19 UTC, Snugug commented on .remarkrc.js
> +    { no: '(-|\s)?tard' }
```suggestion
    { no: '(-|\s)?tard(ed)?' }
```
Adding this at the end should cover everything that ends in `tard` or `tarded`, and let us get rid of stand-alone `retarded`

2022-03-08 17:19 UTC, Snugug commented on .remarkrc.js
> +    { no: 'tribal(-|\s)?division'},
```suggestion
    { no: 'tribal(-|\s|ism)?(knowledge|wisdom|division)?'},
```

Can this and line 33 and 34 be combined, like we do on line 68?

2022-03-08 17:19 UTC, Snugug commented on .remarkrc.js
> +    { no: 'the(-|\s)?natives'},
Can line 42 be updated to include both with and without the the? Something like `(the(-|\s)?)?natives`?

2022-03-16 18:41 UTC, nohe427 commented
@Snugug - Can you take another look?

2022-03-17 20:02 UTC, Snugug approved these changes

2022-03-17 20:02 UTC, Snugug commented
TYVM @nohe427! LGTG

2022-03-17 20:02 UTC, Snugug approved these changes

2022-03-17 20:08 UTC, merged