(💎) site - Community Quotes Module
chromeos/chromeos.dev pull request #334
Opened 2022-03-11 22:50 UTC by nickalcantara

Introduces a new flexible quote module. 

- Resolves #215

2022-03-15 19:23 UTC, Snugug requested changes
Thanks for your work here! While I have concerns about being able to maintain this styling reasonably, that's a function of the complexity of the design, not the implementation, so no changes needed there.

The only comment I have is I believe the author in the blockquote should be wrapped in a `footer` tag; otherwise this looks GTG!

Thanks for your work here!

2022-03-15 19:23 UTC, Snugug commented on site/_components/community-quotes.njk
> +          </cite>
Reading through HTMl tag semantics, I believe this should be wrapped in a `footer` tag to signify that this is the author of the section (quote). See [HTML5 Doctor's `cite` article](http://html5doctor.com/cite-and-blockquote-reloaded/)

2022-03-17 19:10 UTC, nickalcantara commented
Good catch - thanks for the feedback! I've wrapped the `cite` within a `footer` tag.

2022-03-17 19:28 UTC, Snugug approved these changes

2022-03-17 19:28 UTC, merged