💎 (site) Video Cards
chromeos/chromeos.dev pull request #335
Opened 2022-03-12 00:48 UTC by nickalcantara

Introduces a Video card component.

- Resolves #263

2022-03-16 15:11 UTC, Snugug requested changes
Thanks for your work here! A couple comments, but the most important one is the use of the actual YouTube video thumbnails instead of Drive images for the videos.

Thanks!

2022-03-16 17:03 UTC, nickalcantara commented on site/en/_data/home.yml
> +        alt: 'Google IO: Input matters for Chrome OS'
Whoops! While I meant to swap these out for assets that were previously handed off, I didn't know we could do that with YouTube thumbnails! very convenient.

2022-03-17 18:50 UTC, Snugug requested changes
There's one small change here, but otherwise this looks GTG! Also, it looks like there's a merge conflict that should be quick to resolve

2022-03-17 18:50 UTC, Snugug commented on site/sass/components/_video-card.scss
> +      width: 100%;
Can we use `aspect-ratio` here if it's supported? You can use the same TODO that I've got [here](https://github.com/chromeos/chromeos.dev/blob/e2808f28c73473d689623bc93f70bc2d97b6d8d6/site/sass/components/_embed-responsive.scss), or use that class directly if you'd like, for iOS < 15

2022-03-18 14:08 UTC, Snugug commented
@nickalcantara There appear to be merge conflicts here; if you can resolve them I can take another look. Thanks!

2022-03-18 16:19 UTC, nickalcantara commented
@Snugug conflicts resolved!

2022-03-18 20:36 UTC, Snugug requested changes
Looks like my previous comment got missed in the midst of fixing merge conflicts. Can we use `aspect-ratio` instead of the padding hack?

Thanks!

2022-03-18 20:36 UTC, Snugug commented on site/sass/components/_video-card.scss
> +    }
Looks like this comment got missed in the merge conflicts.

Can we use `aspect-ratio` here if it's supported? You can use the same TODO that I've got [here](https://github.com/chromeos/chromeos.dev/blob/e2808f28c73473d689623bc93f70bc2d97b6d8d6/site/sass/components/_embed-responsive.scss), or use that class directly if you'd like, for iOS < 15

2022-03-19 00:00 UTC, nickalcantara commented
> Looks like my previous comment got missed in the midst of fixing merge conflicts. Can we use `aspect-ratio` instead of the padding hack?
> 
> Thanks!

Whoops - updated!

2022-03-21 14:36 UTC, Snugug requested changes
A small rewrite of the `aspect-ratio` that I'm going to accept then merge so we can close this out.

2022-03-21 14:37 UTC, Snugug approved these changes, later dismissed

2022-03-21 14:44 UTC, Snugug approved these changes

2022-03-21 14:53 UTC, merged