💎(site) Add New Design to News Page Hero
chromeos/chromeos.dev pull request #373
Opened 2022-03-25 14:31 UTC by Vanss472

**Please describe what your Pull Request does**

- added new styles for the News hero
- added card eyebrow icons
- increased app logo shadow per design feedback

**Please tag each issue this Pull Request resolves**

- Resolves #346

2022-03-25 16:14 UTC, Snugug requested changes
Thanks for your work here! This is looking great! Just a couple of small adjustments and I think this is GTG!

2022-03-25 16:14 UTC, Snugug commented on site/_components/hero.njk
> +    </section>
I don't think this needs to be wrapped in a section tag; this `article` doesn't have multiple sections, so it can just be a `div`

2022-03-25 16:33 UTC, Vanss472 commented on site/sass/components/_hero.scss
> +    max-width: 40ch;
Yeah, I did try 60ch but ended up liking 40ch. Anyways changed to `60ch`

2022-03-25 16:37 UTC, Vanss472 commented on site/sass/components/_hero.scss
> +    max-width: 40ch;
Actually delete that.. I prefer this `max-width: clamp(40ch, 50vw, 60ch);`

Let me know what you think.

2022-03-25 17:31 UTC, Snugug commented on site/sass/components/_hero.scss
> +    max-width: 40ch;
I like it!

2022-03-25 17:32 UTC, Snugug approved these changes, later dismissed

2022-03-25 23:43 UTC, Vanss472 commented
Hi @Snugug this is ready for review.

I have added:
- [added news hero article and fix body](https://github.com/chromeos/chromeos.dev/pull/373/commits/f5a959644b32589aca0f6124de6b4c5efa7e9767)
- [added styles for stories article hero](https://github.com/chromeos/chromeos.dev/pull/373/commits/17cd42e662692396f3b18374b73924f60fd0a5dc)

2022-03-26 01:33 UTC, Snugug requested changes
One tiny update and then this is GTG

2022-03-26 01:33 UTC, Snugug commented on site/en/stories/stories.json
> -  "tags": ["case study"],
This line needs to be added back or none of the case studies show up on the page

2022-03-26 01:41 UTC, Snugug approved these changes
There are a couple of things I'm going to clean up this weekend to normalize some of the behavior between stories and posts, but I'm not going to block this merge on it.

2022-03-26 01:42 UTC, merged