Home page translation for ES
chromeos/chromeos.dev pull request #397
Opened 2022-03-30 17:55 UTC by tropicadri

ES new home translations

2022-03-30 18:43 UTC, Snugug requested changes
Thanks so much for doing this Adriana! I really appreciate it!

There look to be a few places where I think the merged Spanish file we had didn't match the English version, and some places where I think a translation may have been missed. I think I've pointed them all out in the doc, except for [footnotes](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L196-L201), which are def in the "missing" category that I didn't get moved into this file (and [stats](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L69-L90) will probably need to be updated to point to the right footnote too).

Again, thank you very much for your help here!

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
>      subtitle: Keep your app—and your audience—growing, across the Chrome OS community.
Can you please take a look at this?

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
>      copy: Linux is seamlessly built into Chrome OS so you’ll always be ready whenever inspiration hits.
Can you please take a look at this?

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
> +      desc: Desktop PWA installs , YoY
Can you please take a look at this?

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
>    subtitle: Explore how brands are unlocking more possibilities with Chrome OS.
Can you please take a look at this?

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
>  m100:
Can you please take a look at this? [This](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L97-L107) is the current content for it

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
>  community:
Can you please take a look at this? [This](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L132-L159) is the current content for it.

2022-03-30 18:43 UTC, Snugug commented on site/es/_data/home.yml
>      copy: Learn how your app can power learning experiences for 50 million Chromebooks in the classrooms.
Can you please take a look at this?

2022-04-07 20:38 UTC, Snugug requested changes
Thanks so much for this Adriana! I really really appreciate it!

It looks like there are two items that we added last-minute to the English page that didn't make it into the Spanish YAML. Can you take a look at them?

* [footnotes](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L196-L201) and the matching [footnote number](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L69-L90) in the stats
* The [quotes](https://github.com/chromeos/chromeos.dev/blob/main/site/en/_data/home.yml#L128-L159) in the developers section.

Again, thank you very much for your help here!

2022-04-29 23:52 UTC, tropicadri commented
I double checked quotes and added footnotes. let me know if there is anything missing.

2022-05-06 15:19 UTC, Snugug approved these changes

2022-05-06 15:28 UTC, merged