💎(site) Add New Design to Technical Landing - Body
chromeos/chromeos.dev pull request #408
Opened 2022-04-06 16:12 UTC by Vanss472

- added interest form to tech detail template
- added get started section to tech detail template

**Please tag each issue this Pull Request resolves**

- Resolves #339 
- Resolves #291

@Snugug my bad here I pushed the Technical content changes to the **content/getting-started** branch directly. Let me know if you need me to reverse it. 

Also about the interest form section. In my opinion, it looks better if the CTA is full width rather than what you recommended.

Screenshot if side-by-side:
![Screen Shot 2022-04-06 at 11 52 10 AM](https://user-images.githubusercontent.com/1170192/162018978-5c0d2b81-03de-45ee-a938-95425f1b27be.png)

vs full width:
![image](https://user-images.githubusercontent.com/1170192/162019571-98ace65f-50c9-4de9-84b1-d7c90b8b931e.png)

2022-04-06 19:04 UTC, Snugug requested changes
Thanks for this! I've got a few small comments, but otherwise it looks great!

2022-04-06 19:33 UTC, Vanss472 commented on lib/linting/schemas/technical.js
> +              minLength: 10,
set to `maxLength: 500,`

2022-04-06 19:43 UTC, Vanss472 commented on site/sass/layouts/_tech-detail.scss
> +    }
fixed

2022-04-06 19:43 UTC, Vanss472 commented on site/sass/layouts/_tech-detail.scss
> +      }
fixed

2022-04-06 19:43 UTC, Vanss472 commented on site/_layouts/tech-detail.njk
> +          {{ card.body | markdown | safe }}
done.

2022-04-06 20:34 UTC, Snugug submitted a review, later dismissed

2022-04-06 20:35 UTC, Snugug commented
Thanks for your work here! I'm calling this _done_! I'm not going to merge yet, as I want to update our other sections with getting started content.

2022-04-12 20:21 UTC, Snugug approved these changes

2022-04-12 20:22 UTC, merged